const express = require('express')
const mysql = require('mysql2')
const app = express()
app.use(express.json())
app.use(express.static('public'))
const db = mysql.createConnection({host:'127.0.0.1',port:3306,user:'root',password:'',database:'crm'})
db.connect(e=>{console.log(e?e.message:'DB OK')})
app.get('/leads',(q,r)=>{db.query('SELECT * FROM leads',(e,d)=>{if(e)return r.status(500).json({error:e.message});r.json(d)})})
app.post('/leads',(q,r)=>{const{name,email,source,status,notes}=q.body;db.query('INSERT INTO leads(name,email,source,status,notes)VALUES(?,?,?,?,?)',[name,email,source,status,notes],(e)=>{if(e)return r.status(500).json({error:e.message});r.json({ok:1})})})
app.listen(5000,()=>console.log('ready'))